### ISSUE TITLE
firmware.bin not found

### ISSUE THREAD

**Issue by Markus-Be** [protyposis/yi-mirrorless-firmware-tools#6]
Hi,

i tryed to unpack the firmware.bin but the file is not found.

**Software-Version:** commit b90b96c124a3b076fa0283404e6595a4a40d20d0

**Issue**
`npm run unpack firmware.bin 

> yi-mirrorless-firmware-tools@0.1.0 unpack /home/markus/projekte/yi-Kamera/Firmware_Kamera/yi-mirrorless-firmware-tools
> node index.js unpack 'firmware.bin'
{ Error: ENOENT: no such file or directory, open 'firmware.bin'
    at Object.openSync (fs.js:450:3)
    at readSections (/home/markus/projekte/yi-Kamera/Firmware_Kamera/yi-mirrorless-firmware-tools/firmware.js:120:19)
    at Object.unpack (/home/markus/projekte/yi-Kamera/Firmware_Kamera/yi-mirrorless-firmware-tools/firmware.js:211:5)
    at Object.<anonymous> (/home/markus/projekte/yi-Kamera/Firmware_Kamera/yi-mirrorless-firmware-tools/index.js:28:22)
    at Module._compile (internal/modules/cjs/loader.js:721:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:732:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
    at Function.Module._load (internal/modules/cjs/loader.js:552:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:774:12)
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: 'firmware.bin' }
`

**Workaround**

you need to run the command from the tools folder **NOT** from a subfolder there the Firmware file is.

**Comment by protyposis** [comment]
Yes exactly. What you call workaround is how this is currently designed to be used :)
